name: auratrace_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_database: ^11.3.1
  firebase_auth: ^5.3.4
  provider: ^6.1.2  #current   
  animate_do: ^4.0.0  #current 
  flutter_map: ^7.0.2  #current
  latlong2: ^0.9.1  #current
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2  #current
  geolocator: ^13.0.2  #current
  geocoding: ^3.0.0  #current
  intl: ^0.20.2  #current
  cloud_firestore: ^5.6.5
  flutter_local_notifications: ^19.0.0
  # url_launcher: ^6.3.1 #current
  # permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
